steps:
- name: 'us-east1-docker.pkg.dev/overleaf-ops/ol-docker/deb-builder:latest'
  env: 
  - 'DEBIAN_FRONTEND=noninteractive'
  script: |
    #!/usr/bin/env bash
    mkdir /tmp/librdb
    cp -r  /workspace/. /tmp/librdb
    cd /tmp/librdb
    origtargz
    sudo apt-get update
    mk-build-deps -i --tool="apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends --yes" --root-cmd=sudo --remove
    debuild
    ls -ld /deb
    cp ../librdb_1.0.0-*_amd64.deb /deb/
  volumes:
  - name: 'deb'
    path: '/deb'
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  args:
  - gcloud
  - artifacts 
  - apt 
  - upload
  - ol-deb
  - --location
  - us-east1
  - --source=
  - /deb/librdb_1.0.0-*_amd64.deb
  volumes:
  - name: 'deb'
    path: '/deb'